apiVersion: app.season.io/v1beta1
kind: MyApp
metadata:
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp-sample
    app.kubernetes.io/part-of: opdemo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: opdemo
  name: myapp-sample
spec:
  # TODO(user): Add fields here
